name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{secrets.SERVICE_ACCOUNT}}
          project_id: ${{secrets.SERVICE_ID}}
          workload_identity_provider: ${{secrets.WORKLOAD_ID_PROV}}

      # Build and Deploy
      - name: Build and Deploy
        run: |
          gcloud run deploy game \
            --source . \
            --region europe-west6 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
